[package]
name = "biblatex"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-normalization = "0.1.20"

[dev-dependencies]
criterion = "0.3.6"

[[bench]]
name = "biber_papers"
harness = false